# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
$ ->
  width = 1000
  height = 1000

  vis = d3.select("#graph")
    .append("svg")

  d3.json document.location.href + ".json", (error, graph) ->
    if (error)
      return
    d3Graph().visualize("graph", width, height, graph)

  getContrast = (hexColor) ->
    r = parseInt(hexColor.substr(1,2),16);
    g = parseInt(hexColor.substr(3,2),16);
    b = parseInt(hexColor.substr(5,2),16);
    yiq = ((r * 299) + (g*587) + (b*114))/1000;
    return (yiq > 128);

  $(".calendar").each (a, b) ->
    $(b).css "background-color", $(b).attr "data-colour"
    $(b).css "color", () ->
      getContrast $(b).attr "data-colour" ? "#000000" : "#FFFFFF"


# ---
# generated by js2coffee 2.0.4
